version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cfadmin
      POSTGRES_PASSWORD: A1b2c3d4*
      POSTGRES_DB: BDTEST
    volumes:
      - ./data:/var/lib/postgresql/data
